// Code generated by command: go run x86_encode.go -out ./x86_encode.s -stubs stub.go. DO NOT EDIT.

package x86

// Encodes 8 32-bit unsigned integers at a time.
func x86ControlBytes8(in []uint32) (r uint32)
