// Code generated by command: go run asm.go -out ./x86_encode.s -stubs stub.go. DO NOT EDIT.

package x86

// PutUint32x86_8 encodes 8 32-bit unsigned integers at a time.
func PutUint32x86_8(in []uint32, outBytes []byte, shuffle [][16]uint8, lenTable []uint8) (r uint16)
