// Code generated by command: go run x86_encode.go -out ./x86_encode.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func x86ControlBytes8(in []uint32) uint32
// Requires: AVX, AVX2, SSE2
TEXT ·x86ControlBytes8(SB), NOSPLIT, $0-28
	MOVB         $0x11, CL
	MOVW         $0x7f00, DX
	VPBROADCASTB (CL), X0
	VPBROADCASTW (DX), X1
	MOVQ         in_base+0(FP), CX
	VLDDQU       (CX), X2
	VLDDQU       128(CX), X3
	PMINUB       X0, X2
	PMINUB       X0, X3
	PACKUSWB     X3, X2
	PMINSW       X0, X2
	PADDUSW      X1, X2
	ANDL         $0x00000000, AX
	PMOVMSKB     X2, AX
	MOVL         AX, ret+24(FP)
	RET
