// Code generated by command: go run asm.go -out ./encode_amd64.s. DO NOT EDIT.

#include "textflag.h"

// func put8uint32Fast(in []uint32, outBytes []byte, shuffle *[256][16]uint8, lenTable *[256]uint8) (r uint16)
// Requires: AVX, AVX2
TEXT ·put8uint32Fast(SB), NOSPLIT, $0-66
	VPBROADCASTW mask1111<>+0(SB), X0
	VPBROADCASTW mask7F00<>+0(SB), X1
	MOVQ         in_base+0(FP), AX
	VLDDQU       (AX), X2
	VLDDQU       16(AX), X3
	VPMINUB      X0, X2, X4
	VPMINUB      X0, X3, X5
	VPACKUSWB    X5, X4, X4
	VPMINSW      X0, X4, X4
	VPADDUSW     X1, X4, X4
	VPMOVMSKB    X4, AX
	MOVW         AX, r+64(FP)
	MOVQ         shuffle+48(FP), CX
	MOVBQZX      AL, DX
	SHLQ         $0x04, DX
	ADDQ         CX, DX
	VLDDQU       (DX), X0
	MOVWQZX      AX, DX
	SHRQ         $0x08, DX
	SHLQ         $0x04, DX
	ADDQ         CX, DX
	VLDDQU       (DX), X1
	VPSHUFB      X0, X2, X2
	VPSHUFB      X1, X3, X3
	MOVQ         outBytes_base+24(FP), CX
	MOVQ         CX, DX
	MOVQ         lenTable+56(FP), BX
	MOVBQZX      AL, AX
	ADDQ         BX, AX
	MOVBQZX      (AX), AX
	ADDQ         AX, DX
	VMOVDQU      X2, (CX)
	VMOVDQU      X3, (DX)
	RET

DATA mask1111<>+0(SB)/2, $0x1111
GLOBL mask1111<>(SB), RODATA|NOPTR, $2

DATA mask7F00<>+0(SB)/2, $0x7f00
GLOBL mask7F00<>(SB), RODATA|NOPTR, $2
